export const GET_NEWS_SUCCESS = "GET_NEWS_SUCCESS";
export const GET_NEWS_FAILURE = "GET_NEWS_FAILURE";

export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const GET_COMMENTS_FAILURE = "GET_COMMENTS_FAILURE";

export const GET_ONE_NEWS_SUCCESS = "GET_ONE_NEWS_SUCCESS";
export const GET_ONE_NEWS_FAILURE = "GET_ONE_NEWS_FAILURE";

export const CHANGE_TITLE_NEWS_INPUT_VALUE = "CHANGE_TITLE_NEWS_INPUT_VALUE";
export const CHANGE_NEWS_INPUT_VALUE = "CHANGE_NEWS_INPUT_VALUE";
export const CHANGE_IMAGE_NEWS_INPUT_VALUE = "CHANGE_IMAGE_NEWS_INPUT_VALUE";

export const CHANGE_NAME_COMMENT_INPUT_VALUE = "CHANGE_NAME_COMMENT_INPUT_VALUE";
export const CHANGE_COMMENT_INPUT_VALUE = "CHANGE_COMMENT_INPUT_VALUE";

export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAILURE = "DELETE_COMMENT_FAILURE";

export const DELETE_NEWS_SUCCESS = "DELETE_NEWS_SUCCESS";
export const DELETE_NEWS_FAILURE = "DELETE_NEWS_FAILURE";

export const ADD_NEW_COMMENT_SUCCESS = "ADD_NEW_COMMENT_SUCCESS";
export const ADD_NEW_COMMENT_FAILURE = "ADD_NEW_COMMENT_FAILURE";

export const ADD_NEWS_SUCCESS = "ADD_NEWS_SUCCESS";
export const ADD_NEWS_FAILURE = "ADD_NEWS_FAILURE";